language: csharp
mono: none
sudo: required
dist: trusty
dotnet: 2.0.0
solution: Useful.sln

install:
- cd src
- dotnet restore

script:
 - dotnet build
 - dotnet test Useful.Tests/Useful.Tests.csproj
